package FinancialInterface;


public class ID extends javax.swing.JPanel {

    /**
     * Creates new form ID
     */
    public ID() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 212, 212));
        jLabel1.setText("当前登录：");
        jLabel1.setMaximumSize(new java.awt.Dimension(50, 24));
        add(jLabel1);
        jLabel1.setBounds(10, 10, 90, 24);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 212, 212));
        jLabel2.setText("戚城武");
        jLabel2.setToolTipText("");
        add(jLabel2);
        jLabel2.setBounds(106, 10, 54, 24);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 212, 212));
        jLabel3.setText("ID：");
        add(jLabel3);
        jLabel3.setBounds(178, 10, 37, 24);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 212, 212));
        jLabel4.setText("161250099");
        add(jLabel4);
        jLabel4.setBounds(221, 10, 150, 24);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
