/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FinancialInterface;

import PbbMethod.PbbService;
import java.io.File;

import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import PbbMethod.PbbServiceImpl;
import fileOperate.FileOperation;
import java.util.Timer;
import java.util.TimerTask;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
/**
 *
 * @author Administrator
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddJPanel
     */
     public  String viewserv() throws RemoteException {
        String url = "rmi://localhost:1098/";
        String money="";
        try {
            Context namingContext = new InitialContext();
            PbbService serv = (PbbService) namingContext.lookup(
                    url + "HelloService1");
            money= serv.clientView(name);
        }
        catch (NamingException e) {
            e.printStackTrace();
        }
        return money;
    }
    
    public ViewJPanel() {
        initComponents();
        
    }
    String name;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        setPreferredSize(new java.awt.Dimension(740, 600));
        setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 213, 213));
        jLabel1.setText("查询账户");
        add(jLabel1);
        jLabel1.setBounds(20, 10, 144, 49);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 213, 213));
        jLabel2.setText("账户名称");
        add(jLabel2);
        jLabel2.setBounds(110, 120, 100, 40);

        jLabel3.setFont(new java.awt.Font("微软雅黑", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 213, 213));
        jLabel3.setText("余额");
        add(jLabel3);
        jLabel3.setBounds(130, 200, 70, 40);

        jTextField1.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(260, 120, 270, 40);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(260, 200, 270, 40);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("微软雅黑", 0, 20)); // NOI18N
        jButton1.setText("确定");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(510, 310, 80, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         
         name=jTextField1.getText();
         String money="";
         try {
             money=viewserv();
         } catch (RemoteException ex) {
             Logger.getLogger(ViewJPanel.class.getName()).log(Level.SEVERE, null, ex);
         }
         jLabel4.setText(money);
         Timer timer = new Timer();
                        TimerTask  task = new TimerTask (){
                              public void run() {
                                  jLabel4.setText("");
                                  jTextField1.setText("");
                           }
};
            timer. schedule (task,3000L, 3000L);
       
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
