/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FinancialInterface;

import PbbMethod.PbbService;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import fileOperate.FileOperation;
import java.rmi.RemoteException;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;



/**
 *
 * @author Administrator
 */
public class ZhiChuJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddJPanel
     */
     public  String readserv() throws RemoteException {
        String url = "rmi://localhost:1098/";
        String money="";
        try {
            Context namingContext = new InitialContext();
            PbbService serv = (PbbService) namingContext.lookup(
                    url + "HelloService1");
            money=serv.readShouRuZhiChuLiRun(name);
        }
        catch (NamingException e) {
            e.printStackTrace();
        }
        return money;
    }
     String name;
    public ZhiChuJPanel() {
        initComponents();
        String money; 
   
     
   
    
         try {
              name="销售成本";
              money=readserv();
              jLabel2.setText(money);
              name="商品报损";
              money=readserv();
              jLabel6.setText(money);
              name="商品赠出";
              money=readserv();
              jLabel7.setText(money);
              name="总支出";
              money=readserv();
              jLabel8.setText(money);
         } catch (RemoteException ex) {
             Logger.getLogger(ZhiChuJPanel.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        setPreferredSize(new java.awt.Dimension(740, 600));
        setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 213, 213));
        jLabel1.setText("支出类");
        add(jLabel1);
        jLabel1.setBounds(20, 10, 108, 49);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 20)); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(320, 90, 160, 35);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("微软雅黑", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 213, 213));
        jLabel3.setText("商品类支出：");
        add(jLabel3);
        jLabel3.setBounds(20, 160, 140, 50);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("微软雅黑", 0, 20)); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(320, 170, 160, 35);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("微软雅黑", 0, 20)); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(320, 230, 160, 35);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("微软雅黑", 0, 20)); // NOI18N
        add(jLabel8);
        jLabel8.setBounds(320, 300, 160, 35);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("微软雅黑", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 213, 213));
        jLabel11.setText("销售成本");
        add(jLabel11);
        jLabel11.setBounds(170, 90, 90, 35);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("微软雅黑", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 213, 213));
        jLabel12.setText("商品报损");
        add(jLabel12);
        jLabel12.setBounds(170, 170, 130, 35);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("微软雅黑", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 213, 213));
        jLabel13.setText("商品赠出");
        add(jLabel13);
        jLabel13.setBounds(170, 230, 80, 35);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("微软雅黑", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 213, 213));
        jLabel14.setText("总支出");
        add(jLabel14);
        jLabel14.setBounds(170, 300, 90, 35);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
