/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GM_Frame;

import Admin_Frame.Client;
import Objects.Goods;
import Sale.saleForm;
import java.awt.Toolkit;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.swing.table.DefaultTableModel;
import rmi远程.HacoService;
import salesInterface.Sale;

/**
 *
 * @author Kevin
 */
public class OperatingSchedule extends javax.swing.JFrame {

    /**
     * Creates new form OperatingSchedule
     */
    public int width = Toolkit.getDefaultToolkit().getScreenSize().width;
    public int height = Toolkit.getDefaultToolkit().getScreenSize().height;
    public int windowsWidth = 700;
    public int windowsHeight = 600;
    public OperatingSchedule() {
        initComponents();
        this.setBounds((width - windowsWidth) / 2, (height - windowsHeight) / 2, windowsWidth, windowsHeight);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 213, 213));
        jLabel7.setText("查看经营历程表");
        jLabel7.setToolTipText("");

        jScrollPane1.setFont(new java.awt.Font("微软雅黑", 0, 24)); // NOI18N
        jScrollPane1.setHorizontalScrollBar(null);

        jTable1.setFont(new java.awt.Font("微软雅黑", 0, 24)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 213, 213));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                " 时间", " 单据编号"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setDoubleBuffered(true);
        jTable1.setGridColor(new java.awt.Color(172, 172, 172));
        jTable1.setRowHeight(20);
        jTable1.setSelectionBackground(new java.awt.Color(0, 213, 213));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("宋体", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("类型");

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("微软雅黑", 0, 20)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 213, 213));
        jButton9.setText("查看");
        jButton9.setToolTipText("");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        String time = "";
        switch(OperatingSchedule_S.type){
            case 1:
                jLabel1.setText("销售类");
                ArrayList<String> IDs = new ArrayList<String>();
                try {
                    IDs = Client.serv.GetsaleForms();
                } catch (RemoteException ex) {
                    Logger.getLogger(SalesSchedule.class.getName()).log(Level.SEVERE, null, ex);
                }

                ArrayList<String> ReIDs = new ArrayList<String>();
                try {
                    ReIDs = Client.serv.GetsaleReturnForms();
                } catch (RemoteException ex) {
                    Logger.getLogger(SalesSchedule.class.getName()).log(Level.SEVERE, null, ex);
                }
                tableModel.setRowCount(0);
                for (int i = 0; i < IDs.size(); i++) {
                    String[] arr = new String[2];
                    time = IDs.get(i).split("-")[1];
                    arr[0] = time.substring(0, 4) + "-" + time.substring(4, 6) + "-" + time.substring(6);
                    arr[1] = IDs.get(i);
                    tableModel.addRow(arr);
                }
                for (int i = 0; i < ReIDs.size(); i++) {
                    String[] arr = new String[2];
                    time = ReIDs.get(i).split("-")[1];
                    arr[0] = time.substring(0, 4) + "-" + time.substring(4, 6) + "-" + time.substring(6);
                    arr[1] = ReIDs.get(i);
                    tableModel.addRow(arr);
                }
                jTable1.invalidate();
                break;
            case 2:
                jLabel1.setText("进货类");
                ArrayList<String> SIDs = new ArrayList<String>();
                try {
                    SIDs = Client.serv.GetstockForms();
                } catch (RemoteException ex) {
                    Logger.getLogger(SalesSchedule.class.getName()).log(Level.SEVERE, null, ex);
                }

                ArrayList<String> ReSIDs = new ArrayList<String>();
                try {
                    ReSIDs = Client.serv.GetreturnForms();
                } catch (RemoteException ex) {
                    Logger.getLogger(SalesSchedule.class.getName()).log(Level.SEVERE, null, ex);
                }
                tableModel.setRowCount(0);
                for (int i = 0; i < SIDs.size(); i++) {
                    String[] arr = new String[2];
                    time = SIDs.get(i).split("-")[1];
                    arr[0] = time.substring(0, 4) + "-" + time.substring(4, 6) + "-" + time.substring(6);
                    arr[1] = SIDs.get(i);
                    tableModel.addRow(arr);
                }
                for (int i = 0; i < ReSIDs.size(); i++) {
                    String[] arr = new String[2];
                    time = ReSIDs.get(i).split("-")[1];
                    arr[0] = time.substring(0, 4) + "-" + time.substring(4, 6) + "-" + time.substring(6);
                    arr[1] = ReSIDs.get(i);
                    tableModel.addRow(arr);
                }
                jTable1.invalidate();
                break;
            case 3:
                jLabel1.setText("财务类");
                break;
            case 4:
                jLabel1.setText("库存类");
                break;
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
       int index=jTable1.getSelectedRow();
       String ID = (String)tableModel.getValueAt(index,1);
       
       
       String tmp = ID.substring(0, 3);
       if(tmp.equals("XSD")){
        try {
            saleForm a = Client.serv.searchSaleForm(ID);
            Sale b = new Sale(); b.run(a);
        }
        catch (Exception e) {}
           
           
           
           
       }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperatingSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperatingSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperatingSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperatingSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperatingSchedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
